version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mqtt
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 228325602
      DB_NAME: attendance_system
      MQTT_HOST: mqtt
      MQTT_PORT: 1883

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228325602
      POSTGRES_DB: attendance_system
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001" # Для вебсокетів (за потреби)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  db_data:
